### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to PubNub\Exceptions\PubNubUnsubscribeException::setChannels()

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-php#68]
This is the first time that I use RingCentral PHP SDK. Everything worked fine until I tried PubNub

```php
$subscription = $rcsdk->createSubscription();
$subscription->addEvents(array('/restapi/v1.0/account/~/extension/~/message-store/instant?type=SMS'));
$subscription->addListener(Subscription::EVENT_NOTIFICATION, function (NotificationEvent $e) {
    print_r($e->getPayload());
});

$apiResponse = $subscription->register();
```

```
[2018-05-03 08:25:30] PubNub.DEBUG: GET https://ps.pndsn.com/v2/subscribe/sub-c-b8b9cd8c-e906-11e2-b383-02ee2ddab7fe/1116154513890231_8370446d/0?pnsdk=PubNub-PHP%2F4.0.0&uuid=4A9EE615-4764-4BC8-B780-88353F9D7282 {"method":"Subscribe"} []
[2018-05-03 08:25:30] PubNub.DEBUG: Response body: {"t":{"t":"15253359305298380","r":4},"m":[]} {"method":"Subscribe","statusCode":200} []

Fatal error: Uncaught TypeError: Argument 1 passed to PubNub\Exceptions\PubNubUnsubscribeException::setChannels() must be of the type array, string given,called in /Users/tyler.liu/src/php/sms-api-php-quickstart/vendor/ringcentral/ringcentral-php/src/Subscription/Subscription.php on line 35 and defined in /Users/tyler.liu/src/php/sms-api-php-quickstart/vendor/pubnub/pubnub/src/PubNub/Exceptions/PubNubUnsubscribeException.php:32
Stack trace:
#0 /Users/tyler.liu/src/php/sms-api-php-quickstart/vendor/ringcentral/ringcentral-php/src/Subscription/Subscription.php(35): PubNub\Exceptions\PubNubUnsubscribeException->setChannels('111615451389023...')
#1 /Users/tyler.liu/src/php/sms-api-php-quickstart/vendor/pubnub/pubnub/src/PubNub/Managers/ListenerManager.php(57): RingCentral\SDK\Subscription\PubnubCallback->status(Object(PubNub\PubNub), Object(PubNub\Models\ResponseHelpers\PNStatus))
#2 /Users/tyler.liu/src/php/sms-api-php-quickstart/vendor/pubnub/pubnub/src/PubNub/Managers/SubscriptionManager.php(118): PubNub\Managers\Listener in /Users/tyler.liu/src/php/sms-api-php-quickstart/vendor/pubnub/pubnub/src/PubNub/Exceptions/PubNubUnsubscribeException.php on line 32
```

I think 
https://github.com/ringcentral/ringcentral-php/blob/master/src/Subscription/Subscription.php#L50
should be changed to `$e->setChannels(array($sub['deliveryMode']['address']));`

**Comment by kirill-konshin** [comment]
Is it still an issue?

**Comment by tylerlong** [comment]
It is no longer an issue.  We have confirmed that Pubnub works.
